### ISSUE TITLE
皮肤墙报错

### ISSUE THREAD

**Issue by FlashKiana** [KimigaiiWuyi/WzryUID#8]
07 15:31:47 [INFO] plugins.WzryUID.WzryUID.wzryuid_skin_show | [皮肤墙] uid:70409511
09-07 15:31:49 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]开始下载: 山海·琳琅生_10608.png | 地址: https://game-1255653016.file.myqcloud.com/battle_skin_702-1236/10608.jpg
09-07 15:31:49 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]下载成功: 山海·琳琅生_10608.png
09-07 15:31:49 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]开始下载: label_limited_2023newyear.png | 地址: http://camp.qq.com/web/skin/label_limited_2023newyear.png
09-07 15:31:49 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]下载成功: label_limited_2023newyear.png
Task exception was never retrieved
future: <Task finished name='Task-8633' coro=<send_wzry_skin_list() done, defined at C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py:14> exception=AttributeError("'NoneType' object has no attribute 'size'")>
Traceback (most recent call last):
  File "C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py", line 20, in send_wzry_skin_list
    im = await _get_skin_list(ev.user_id, uid)
  File "C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 115, in _get_skin_list
    if label.size == (95, 46):
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by KimigaiiWuyi** [comment]
推断应该是网络问题导致没下完，我这边正常；
如果可以的话需要修改gsuid_core/gsuid_core/config.json下的`log``level`为`DEBUG`，保存重启后然后查看后台输出，即可看到网络访问请求，这样方便定位问题
![f2951095f7dba86bd2d9dfe701835586](https://github.com/KimigaiiWuyi/WzryUID/assets/55526518/17162bc4-4206-4291-9eb4-8d407ea2d59c)

**Comment by FlashKiana** [comment]
Icon': 'http://shp.qpic.cn/tgos/1025/8a85ab19b0f401c3e832d99efedfdbab/0', 'szSmallIcon': 'http://shp.qpic.cn/tgos/577/df93a0307701162dc80363a12781279a/0', 'szAppendProp': '法术攻击+10', 'iBuy': 1, 'isHidden': 0, 'szDesc': '王昭君:乞巧织情', 'szClass': 'S+', 'iPrice': 1688, 'skin_worth': None, 'szLabelTitle': None, 'szIcon': None, 'publish_time': None, 'dtEventTime': '2021-08-11 16:08:24', 'iId': 692, 'szHeroTitle': '王昭君', 'classLabel': 'http://camp.qq.com/web/skin/label_ss.png', 'goodsId': '', 'classType': ['2', '42'], 'classTypeName': ['传说品质', '荣耀中国节'], 'accessWay': '', 'preUptime': 1628784000, 'bigCover': 'https://pvppic.kohsocialapp.qq.com/wzzs_pic/0/c7e7c439ed15d28ec0bc0303bade3d96/0'}}}}
09-07 18:10:42 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]开始下载: 神器·明辉仪_13604.png | 地址: https://game-1255653016.file.myqcloud.com/battle_skin_702-1236/13604.jpg
09-07 18:10:43 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]下载成功: 神器·明辉仪_13604.png
09-07 18:10:43 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]开始下载: label_limited_yongningjizhizun.png | 地址: http://camp.qq.com/web/skin/label_limited_yongningjizhizun.png
09-07 18:10:43 [INFO] plugins.WzryUID.WzryUID.utils.download | [wzry]下载成功: label_limited_yongningjizhizun.png
Task exception was never retrieved
future: <Task finished name='Task-698' coro=<send_wzry_skin_list() done, defined at C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py:14> exception=AttributeError("'NoneType' object has no attribute 'size'")>
Traceback (most recent call last):
  File "C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py", line 20, in send_wzry_skin_list
    im = await _get_skin_list(ev.user_id, uid)
  File "C:\nb\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 115, in _get_skin_list
    if label.size == (95, 46):
AttributeError: 'NoneType' object has no attribute 'size'
09-07 18:10:45 [SUCCESS] nonebot | OneBot V11 206842378 | [message.group.normal]: Message 1290896710 from 3026706487@[群:607768397] '到能玩一整把'
09-07 18:10:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
09-07 18:10:45 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
09-07 18:10:45 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
09-07 18:10:45 [INFO] gsuid_core.handler | [Raw] raw_text=到能玩一整把, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=206842378, msg_id=1290896710, user_type=group, group_id=607768397, user_id=3026706487, user_pm=6, content=[Message(type='text', data='到能玩一整把')],
09-07 18:10:48 [SUCCESS] nonebot | OneBot V11 206842378 | [message.group.normal]: Message 233331141 from 3026706487@[群:607768397] '很赚吧'
09-07 18:10:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
09-07 18:10:48 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
09-07 18:10:48 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
09-07 18:10:48 [INFO] gsuid_core.handler | [Raw] raw_text=很赚吧, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=206842378, msg_id=233331141, user_type=group, group_id=607768397, user_id=3026706487, user_pm=6, content=[Message(type='text', data='很 赚吧')],
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_start\__init__.py", line 11, in all_start
    await startup()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_resource\__init__.py", line 25, in startup
    await download_all_resource()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_cos())
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 72, in download_all_file_from_cos
    await _download(TASKS)
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 25, in _download
    list(filter(lambda x: x is not None, await asyncio.gather(*tasks)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
None
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_start\__init__.py", line 11, in all_start
    await startup()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_resource\__init__.py", line 25, in startup
    await download_all_resource()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_cos())
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 72, in download_all_file_from_cos
    await _download(TASKS)
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 25, in _download
    list(filter(lambda x: x is not None, await asyncio.gather(*tasks)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_start\__init__.py", line 11, in all_start
    await startup()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_resource\__init__.py", line 25, in startup
    await download_all_resource()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_cos())
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 72, in download_all_file_from_cos
    await _download(TASKS)
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 25, in _download
    list(filter(lambda x: x is not None, await asyncio.gather(*tasks)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
None
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_start\__init__.py", line 11, in all_start
    await startup()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_resource\__init__.py", line 25, in startup
    await download_all_resource()
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_cos())
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 72, in download_all_file_from_cos
    await _download(TASKS)
  File "C:\nb\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\utils\resource\download_from_cos.py", line 25, in _download
    list(filter(lambda x: x is not None, await asyncio.gather(*tasks)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
09-07 18:10:49 [SUCCESS] nonebot | OneBot V11 206842378 | [message.group.normal]: Message 787080192 from 3026706487@[群:607768397] '[image:file=2cd7b260704a362d9addcccaf229188928991-516-444.jpg,subType=1,url=https://gchat.qpic.cn/gchatpic_new/3026706487/607768397-2870248538-...]'
09-07 18:10:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
09-07 18:10:49 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
09-07 18:10:49 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
09-07 18:10:49 [INFO] gsuid_core.handler | [Raw] raw_text=, image=https://gchat.qpic.cn/gchatpic_new/3026706487/607768397-2870248538-2CD7B260704A362D9ADDCCCAF2291889/0?term=2&is_origin=0, at=None, image_list=https://gchat.qpic.cn/gchatpic_new/3026706487/607768397-2870248538-2CD7B260704A362D9ADDCCCAF2291889/0?term=2&is_origin=0, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=206842378, msg_id=787080192, user_type=group, group_id=607768397, user_id=3026706487, user_pm=6, content=[Message(type='image', data='htt

**Comment by KimigaiiWuyi** [comment]
是不是下载的文件损坏了？可以看看data里的skin或者icon文件夹中是否有损坏文件

**Comment by VsentK** [comment]
同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启

**Comment by KimigaiiWuyi** [comment]
> 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启

重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）

**Comment by VsentK** [comment]
> > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> 
> 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）

不行，重启后输入皮肤墙指令还是无法处理

**Comment by KimigaiiWuyi** [comment]
> > > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> > 
> > 
> > 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）
> 
> 不行，重启后输入皮肤墙指令还是无法处理

尝试清空gsuid_core/data/wzryuid/skin文件夹或者icon文件夹是否可以正常生成呢

**Comment by VsentK** [comment]
> > > > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> > > 
> > > 
> > > 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）
> > 
> > 
> > 不行，重启后输入皮肤墙指令还是无法处理
> 
> 尝试清空gsuid_core/data/wzryuid/skin文件夹或者icon文件夹是否可以正常生成呢

还是不行

**Comment by KimigaiiWuyi** [comment]
> > > > > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> > > > 
> > > > 
> > > > 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）
> > > 
> > > 
> > > 不行，重启后输入皮肤墙指令还是无法处理
> > 
> > 
> > 尝试清空gsuid_core/data/wzryuid/skin文件夹或者icon文件夹是否可以正常生成呢
> 
> 还是不行

你的错误uid呢，我试一下我这边，上面那位我测试没问题无法复现欸

**Comment by VsentK** [comment]
> > > > > > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> > > > > 
> > > > > 
> > > > > 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）
> > > > 
> > > > 
> > > > 不行，重启后输入皮肤墙指令还是无法处理
> > > 
> > > 
> > > 尝试清空gsuid_core/data/wzryuid/skin文件夹或者icon文件夹是否可以正常生成呢
> > 
> > 
> > 还是不行
> 
> 你的错误uid呢，我试一下我这边，上面那位我测试没问题无法复现欸

UID：212948026（难道是我皮肤太多了？

**Comment by KimigaiiWuyi** [comment]
> > > > > > > 同样遇到了相同的问题，并且触发之后其他指令也无法响应了，只能重启
> > > > > > 
> > > > > > 
> > > > > > 重启后再次触发指令是否可以继续往下跑（下载那些皮肤啥的）
> > > > > 
> > > > > 
> > > > > 不行，重启后输入皮肤墙指令还是无法处理
> > > > 
> > > > 
> > > > 尝试清空gsuid_core/data/wzryuid/skin文件夹或者icon文件夹是否可以正常生成呢
> > > 
> > > 
> > > 还是不行
> > 
> > 
> > 你的错误uid呢，我试一下我这边，上面那位我测试没问题无法复现欸
> 
> UID：212948026（难道是我皮肤太多了？

已定位问题，并已修复，请更新后重启查看是否正常
